"""
Django settings for limaBackend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent
# BASE_DIR = Path(__file__).resolve().parent.parent

# lima-backend/
PROJECT_DIR = BASE_DIR.parent
# LimaBlocks/ (repo root, one .env shared with docker compose)
REPO_DIR = PROJECT_DIR.parent


def _load_dotenv():
    """Read .env files into os.environ for runs outside docker compose.

    Real environment variables always win, so compose's `environment:` and
    `env_file:` entries are never overwritten by a stale file on a mounted
    volume. The repo-root .env is read first and the backend-local one after,
    which means lima-backend/.env can override the shared file.
    """
    try:
        from dotenv import load_dotenv
    except ImportError:  # python-dotenv not installed: rely on the real env
        return
    for candidate in (REPO_DIR / ".env", PROJECT_DIR / ".env"):
        if candidate.is_file():
            load_dotenv(candidate, override=False)


_load_dotenv()


def env(name, default=None):
    """Environment variable as a string, with empty treated as unset."""
    value = os.environ.get(name, "")
    return value.strip() if value.strip() else default


def env_bool(name, default=False):
    value = env(name)
    if value is None:
        return default
    return value.lower() in ("1", "true", "yes", "on")


def env_list(name, default=()):
    value = env(name)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret!
# Never committed: it comes from .env (see .env.example). A throwaway key is
# generated for DEBUG runs so a fresh clone starts without any setup, but a
# non-DEBUG run has to be given a real one.
SECRET_KEY = env("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off. "
            "Copy .env.example to .env and fill it in."
        )
    from django.core.management.utils import get_random_secret_key

    SECRET_KEY = get_random_secret_key()

# Empty by default, which under DEBUG lets Django serve localhost only.
# Containers set DJANGO_ALLOWED_HOSTS so the service is also reachable by its
# compose service name.
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")

# Public addresses of the two services. The frontend one drives CORS below.
BACKEND_URL = env("BACKEND_URL", "http://localhost")
BACKEND_PORT = env("BACKEND_PORT", "8000")
FRONTEND_URL = env("FRONTEND_URL", "http://localhost")
FRONTEND_PORT = env("FRONTEND_PORT", "3000")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3rd party apps
    "rest_framework",
    "corsheaders",
    # Local apps
    "digital_regulation",
    "verification",
    "check_engine",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # #rd party middleware
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'limaBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'limaBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# SQLite by default; DB_ENGINE/DB_USER/DB_PASSWORD in .env switch the project
# onto a server database without touching this file.
DB_ENGINE = env("DB_ENGINE", "django.db.backends.sqlite3")

if DB_ENGINE.endswith("sqlite3"):
    DB_NAME = BASE_DIR / env("DB_NAME", "db.sqlite3")
else:
    DB_NAME = env("DB_NAME", "lima")

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': DB_NAME,
        'USER': env("DB_USER", ""),
        'PASSWORD': env("DB_PASSWORD", ""),
        'HOST': env("DB_HOST", ""),
        'PORT': env("DB_PORT", ""),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = env("DJANGO_LANGUAGE_CODE", "en-us")

TIME_ZONE = env("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# django-cors-headers
# The frontend's own origin is always allowed; CORS_ALLOWED_ORIGINS in .env adds
# any others (comma separated) without having to edit this file.

CORS_ALLOWED_ORIGINS = list(dict.fromkeys(
    [f"{FRONTEND_URL}:{FRONTEND_PORT}"]
    + env_list("CORS_ALLOWED_ORIGINS", default=("http://localhost:3000",))
))

# Rest Framework config
REST_FRAMEWORK = {
    "DATETIME_FORMAT": "%Y/%m/%d %H:%M:%S",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
}

# File storage config
MEDIA_URL = env("MEDIA_URL", "/media/")
# Relative values are resolved against BASE_DIR; an absolute path (a mounted
# volume, say) is used as given.
MEDIA_ROOT = os.path.join(BASE_DIR, env("MEDIA_ROOT", "media"))

# Information requirements config
# The IDS an uploaded model is checked against when it is attached to a
# verification. Relative values resolve against PROJECT_DIR - not BASE_DIR,
# which points at the settings package rather than the repository - so a
# deployment can swap in its own specifications without touching the code.
IDS_SPECIFICATIONS_PATH = os.path.join(
    PROJECT_DIR,
    env("IDS_SPECIFICATIONS_PATH",
        os.path.join("verification", "information_requirements",
                     "LiMABlocks_specifications.ids")))
